"""empty message

Revision ID: b2715552a7ea
Revises:
Create Date: 2023-09-14 13:28:59.451951

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2715552a7ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'countries',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('pk')
    )
    op.create_table(
        'cities',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['country_id'], ['countries.pk'], ),
        sa.PrimaryKeyConstraint('pk')
    )
    op.create_table(
        'users',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('birth_date', sa.Date(), nullable=False),
        sa.Column('city_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['city_id'], ['cities.pk'], ),
        sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('cities')
    op.drop_table('countries')
    # ### end Alembic commands ###
