"""empty message

Revision ID: ea0b8bdaec50
Revises: ac84c65dce92
Create Date: 2023-10-03 17:18:41.634856

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea0b8bdaec50'
down_revision: Union[str, None] = 'ac84c65dce92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chats',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column(
            'chat_type',
            sa.Enum('DIRECT', 'GROUP', 'SELF', name='chattype'),
            nullable=False,
        ),
        sa.Column('last_message_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['last_message_id'], ['users.pk'], ),
        sa.PrimaryKeyConstraint('pk')
    )
    op.create_table(
        'chats_to_users',
        sa.Column('chat_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.pk'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.pk'], )
    )
    op.create_table(
        'messages',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('date_time', sa.DateTime(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.pk'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.pk'], ),
        sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.pk'], ),
        sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chats_to_users')
    op.drop_table('chats')
    # ### end Alembic commands ###
